name: jp_screen_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  customizable_counter: ^1.0.4
  flutter_sficon: ^1.1.2
  flutter_svg: ^2.0.10+1
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon/snackApp_icon.png"

flutter:
  uses-material-design: true
  assets:
  - assets/images/details/
  - assets/images/grafiken/
  - assets/images/hintergründe/
  - assets/images/grafiken/cupcakes_cat.png
